from pathlib import Path
from textwrap import dedent


def write_openfoam_case_placeholder(plate, case_dir: str | Path) -> Path:
    """Write a minimal OpenFOAM case scaffold."""
    case = Path(case_dir)
    (case / "0").mkdir(parents=True, exist_ok=True)
    (case / "constant").mkdir(parents=True, exist_ok=True)
    (case / "system").mkdir(parents=True, exist_ok=True)
    (case / "README.md").write_text(dedent(f"""
        # OpenFOAM scaffold for {plate.name}

        This scaffold was generated by ColdCircuit.

        It is not a complete CFD model yet. Add mesh, boundary patches, transport properties, fvSchemes/fvSolution and CHT setup if required.

        Suggested solver path:
        - incompressible single-phase: simpleFoam / pisoFoam for flow screening;
        - CHT: chtMultiRegionFoam for final thermal validation.
        """).strip() + "\n", encoding="utf-8")
    (case / "constant" / "designProperties.json").write_text(plate.model_dump_json(indent=2), encoding="utf-8")
    (case / "system" / "controlDict").write_text(dedent("""
        FoamFile
        {
            version     2.0;
            format      ascii;
            class       dictionary;
            object      controlDict;
        }

        application     simpleFoam;
        startFrom       startTime;
        startTime       0;
        stopAt          endTime;
        endTime         1000;
        deltaT          1;
        writeControl    timeStep;
        writeInterval   100;
        purgeWrite      0;
        writeFormat     ascii;
        writePrecision  6;
        writeCompression off;
        timeFormat      general;
        timePrecision   6;
        runTimeModifiable true;
        """).lstrip(), encoding="utf-8")
    return case
